version: '3'
services:
  model:
    image: 'postgres:latest'
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Sebastian
    ports:
      - '5432:5432'
    networks:
      - red
  backend:
    build: .
    ports:
      - '8080:8080'
    links:
      - model
    volumes:
      - "./source:/home/app"
    networks:
      - red
volumes:
  postgres-data:

networks:
  red:
    driver: bridge
